# This is the Build docker-compose.yml file. You can build and Run ChurchCRM
# from this file by first filling in your password and db info in the .env
# file and then running "docker-compose up -d" in terminal.

version: '3.5'

services:

  mysql:
    container_name: mysql
    image: mariadb:${MYSQL_VER:-10.3}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysqlRoot}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-churchcrmDB}
      MYSQL_USER: ${MYSQL_USER:-churchcrm}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysqlPWD}
    volumes:
      ## keep database
      - mysql_data:/var/lib/mysql

  php:
    container_name: php
    image: devilbox/php-fpm:${PHP_VER:-7.2}-prod
    depends_on:
      - mysql
    environment:
      ## version can be latest or 3.2.3 ...
      CRM_RELEASE_VERSION: ${CRM_VER:-latest}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-churchcrmDB}
      MYSQL_USER: ${MYSQL_USER:-churchcrm}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysqlPWD}
      FORWARD_PORTS_TO_LOCALHOST: '3306:mysql:3306, 80:apache:80, 443:apache:443'
      DOCKER_LOGS: 0
#      DEBUG_RUNTIME: 1
#      DEBUG_ENTRYPOINT: 1
    entrypoint: ["bash", "-c", "/init.sh"]
    volumes:
      - ./www:/var/www/default
      - ./crm_init.sh:/init.sh
      ## enabled by setting DOCKER_LOGS: 0
      - ./log/php:/var/log/php
      ## used when enable email catch-all
      - mail:/var/mail

  apache:
    container_name: apache
    image: devilbox/apache-${APACHE_VER:-2.4}
    links:
      - mysql
      - php
    environment:
      PHP_FPM_ENABLE: 1
      PHP_FPM_SERVER_ADDR: php
      PHP_FPM_SERVER_PORT: 9000
      MAIN_VHOST_ENABLE: 1
      MAIN_VHOST_SSL_GEN: 1
      MAIN_VHOST_SSL_TYPE: both
      MAIN_VHOST_SSL_CN: localhost
      MAIN_VHOST_DOCROOT: churchcrm
#      DOCKER_LOGS: 1
#      DEBUG_RUNTIME: 1
#      DEBUG_ENTRYPOINT: 2
    volumes:
      - ./www:/var/www/default
      ## for keep certs
      - ./cert:/etc/httpd/cert/main
      - ca:/ca
      - httpd:/shared/httpd
    ports:
      - "80:80"
      - "443:443"

volumes:
  mysql_data: null
  ca: null
  mail: null
  httpd: null
