version: '2'
services:
  churchcrm:
    container_name: churchcrm
    build: .
    ports:
      - "80:80"
      - "443:443"
    links:
      - crm-mariadb
  crm-mariadb:
    container_name: crm-mariadb
    image: nimmis/alpine-mariadb
    volumes:
      - /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: churchcrm
      MARIADB_USER: churchcrm
      MARIADB_PASSWORD: my-secret-pw
