version: '2'
services:
  churchcrm:
    build: .
    ports:
      - "80:80"
      - "443:443"
    links:
      - crm-mariadb
  crm-mariadb:
    image: mariadb:latest
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: churchcrm
      MYSQL_USER: churchcrm
      MYSQL_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
