# This is the Build docker-compose.yml file. You can directly run ChurchCRM
# in docker with the main docker-compose.yml file or through the RUN commands
# explained in the README file

version: '2'

services:

  database: #Name of DB Host
    container_name: database
    image: nimmis/alpine-mariadb
    env_file:
      - .env

  churchcrm:
    container_name: churchcrm
    build: ./build-files
    ports:
      - "80:80"
    env_file:
      - .env
